export const SITES = [
  {
    name: "Acopio Ayuda",
    desc: "Plataforma de acopio: registra puntos de recolección y modo de ayuda ofrecida.",
    url: "https://acopio-ayuda.up.railway.app/?modo=ayuda",
    cities: ["Nacional"],
    types: ["ofrece", "directorio"],
  },
  {
    name: "Red Ayuda Manizales",
    desc: "Resultados y registros de ayuda para la ciudad de Manizales.",
    url: "https://redayudamanizales.com/resultados",
    cities: ["Manizales"],
    types: ["directorio"],
  },
  {
    name: "Mapa de Emergencia",
    desc: "Mapa interactivo de puntos de emergencia reportados.",
    url: "https://mapa-emergencia.artefactofilms.workers.dev/",
    cities: ["Nacional"],
    types: ["mapa"],
  },
  {
    name: "Reporta Pereira",
    desc: "Reportes ciudadanos de necesidades y afectaciones en Pereira.",
    url: "https://www.reportapereira.com/",
    cities: ["Pereira"],
    types: ["necesita"],
  },
  {
    name: "Red Sismo",
    desc: "Plataforma general de coordinación de ayuda ante el sismo.",
    url: "https://redsismo.com/",
    cities: ["Nacional"],
    types: ["directorio"],
  },
  {
    name: "SOS Buenaventura",
    desc: "Formulario para ofrecer ayuda en Buenaventura.",
    url: "https://sosbuenaventura.online/ofrecer",
    cities: ["Buenaventura"],
    types: ["ofrece"],
  },
  {
    name: "Terremoto Cali · Puntos Críticos",
    desc: "Mapa de puntos críticos y zonas afectadas en Cali.",
    url: "https://terremoto-cali-puntos-criticos.netlify.app/",
    cities: ["Cali"],
    types: ["mapa"],
  },
  {
    name: "Pereira Unida",
    desc: "Plataforma comunitaria de coordinación de ayuda en Pereira.",
    url: "https://pereira-unida.vercel.app/",
    cities: ["Pereira"],
    types: ["directorio"],
  },
  {
    name: "Ayudas Pereira",
    desc: "Registro de ayudas disponibles y solicitadas en Pereira.",
    url: "https://ayudaspereira.com/",
    cities: ["Pereira"],
    types: ["directorio"],
  },
];
