export const SITES = [
  {
    name: "UNGRD · Gestión del Riesgo",
    desc: "Portal oficial de la Unidad Nacional para la Gestión del Riesgo de Desastres. Información institucional y orientación sobre la respuesta a emergencias en Colombia.",
    url: "https://portal.gestiondelriesgo.gov.co/",
    cities: ["Nacional"],
    official: true,
  },
  {
    name: "Cruz Roja Colombiana",
    desc: "Canal oficial de la Cruz Roja Colombiana para conocer su labor humanitaria y realizar donaciones destinadas a apoyar sus acciones de ayuda.",
    url: "https://www.cruzrojacolombiana.org/",
    cities: ["Nacional"],
    official: true,
  },
  {
    name: "Asocapitales · Terremoto en Colombia",
    desc: "Página de la Asociación Colombiana de Ciudades Capitales con información consolidada sobre ayudas y recursos publicados por fuentes oficiales.",
    url: "https://www.asocapitales.co/terremoto-colombia.html",
    cities: ["Nacional"],
    official: true,
  },
  {
    name: "Servicio Geológico Colombiano · Sismos",
    desc: "Información oficial sobre sismos registrados en Colombia, incluyendo magnitud, ubicación, profundidad y otros datos del evento.",
    url: "https://www.sgc.gov.co/sismos",
    cities: ["Nacional"],
    official: true,
  },
  {
    name: "SGC · Sismo Sentido",
    desc: "Formulario oficial para reportar cómo se sintió un sismo. Los reportes ayudan al SGC a evaluar la intensidad del evento.",
    url: "https://sismosentido.sgc.gov.co/",
    cities: ["Nacional"],
    official: true,
  },

  // SITIOS COMUNITARIOS

  {
    name: "Ayudas Pereira",
    desc: "Registro de ayudas disponibles y solicitadas en Pereira.",
    url: "https://ayudaspereira.com/",
    cities: ["Pereira"],
    types: ["directory"],
  },
  {
    name: "Red de Acopio",
    desc: "Plataforma de acopio, registra puntos de recolección y modo de ayuda ofrecida.",
    url: "https://acopio-ayuda.up.railway.app/?modo=ayuda",
    cities: ["Nacional"],
    types: ["offers", "directory"],
  },
  {
    name: "Ubica tu Peludo",
    desc: "Plataforma de emergencia en Colombia para reunir mascotas tras un sismo.",
    url: "https://encuentratupeludo.vercel.app/",
    cities: ["Nacional"],
    types: ["needs", "offers", "pets", "directory"],
  },
  {
    name: "Red Ayuda Manizales",
    desc: "Resultados y registros de ayuda para la ciudad de Manizales.",
    url: "https://redayudamanizales.com/resultados",
    cities: ["Manizales"],
    types: ["needs", "offers", "pets", "directory"],
  },
  {
    name: "Mapa de Emergencia",
    desc: "Mapa interactivo de puntos de emergencia reportados.",
    url: "https://mapa-emergencia.artefactofilms.workers.dev/",
    cities: ["Nacional"],
    types: ["needs", "map"],
  },
  {
    name: "Reportes Pereira - RADIOGRAFÍA",
    desc: "Reportes ciudadanos de necesidades y afectaciones en Pereira.",
    url: "https://www.reportapereira.com/",
    cities: ["Pereira"],
    types: ["needs", "map"],
  },
  {
    name: "Ayudas Pereira",
    desc: "Registro de ayudas disponibles y solicitadas en Pereira.",
    url: "https://ayudaspereira.com/",
    cities: ["Pereira"],
    types: ["directory"],
  },
  {
    name: "SOS Buenaventura",
    desc: "Herramienta ciudadana para organizar la respuesta en Buenaventura.",
    url: "https://sosbuenaventura.online",
    cities: ["Buenaventura"],
    types: ["needs", "offers"],
  },
  {
    name: "Auxilio Sísmico Colombia",
    desc: "Herramienta comunitaria no oficial.",
    url: "https://redsismo.com/",
    cities: ["Nacional"],
    types: ["needs", "offers", "directory"],
  },
  {
    name: "Terremoto Cali · Puntos Críticos",
    desc: "Coordinación de ayuda",
    url: "https://terremoto-cali-puntos-criticos.netlify.app",
    cities: ["Cali"],
    types: ["map", "needs"],
  },
  {
    name: "Pereira Unida",
    desc: "Plataforma comunitaria de coordinación de ayuda en Pereira.",
    url: "https://pereira-unida.vercel.app/",
    cities: ["Pereira"],
    types: ["needs", "offers", "directory"],
  },
];
